### ISSUE TITLE
`<template if=` is not a guard

### ISSUE THREAD

**Issue by pjjjv** [pjjjv/Akepot#1]
In admin edit mode, when removing all competences from a subcategory:

```
Exception: Uncaught Error: RangeError: index (0) must be in the range [0..0)
Stack Trace:
#0      List.[] (dart:core-patch/growable_array.dart:136)
#1      ObservableList.[] (package:observe/src/observable_list.dart:90:49)
#2      IndexObserver._updateSelf (package:polymer_expressions/eval.dart:754:27)
#3      ExpressionObserver._observe (package:polymer_expressions/eval.dart:315:16)
#4      ExpressionObserver._invalidate (package:polymer_expressions/eval.dart:296:13)
#5      IndexObserver._updateSelf.<anonymous closure> (package:polymer_expressions/eval.dart:759:65)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#9      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:370)
#10     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:312)
#11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:369)
#12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:237)
#13     deliverListChanges (package:observe/src/observable_list.dart:265:23)
#14     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#15     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#16     _handleMutation (dart:html:42316)
```

Harmless exception.
This is because the polymer expression inside a `template if` is still executed and there is an OOB error because length = 0:

```
        <template if="{{ project.categories.length > category_nr }}">
          <section-edit-category category="{{project.categories[category_nr]}}" page="{{page}}" index="{{subcategory_nr}}"></section-edit-category>
```

More: https://github.com/Polymer/polymer/issues/265

**Comment by pjjjv** [comment]
I explored ways to solve it, with changd listeners, expression filter functions (just functions, not even filters), as well as computed properties. They all only solve the problem partially. So it is hard to fix. Especially since in polymer 1.0 this will behave differently.
